branches:
  only:
    - travis

language: python

python:
  - 2.7
  - 3.5

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 1024x768x24 > /dev/null 2>&1 &
  - pip install -r requirements.txt

script:
  - pytest
