branches:
  only:
    - travis

language: python

python:
  - 2.7
  - 3.5

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "./MNIST/download_modelfile.sh"
  - "mv 20160818_MNIST.model MNIST/."

install:
  - pip install -r requirements.txt

script:
  - pytest
